/** @type {import('jest').Config} */
const config = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests', '<rootDir>/src'],
  moduleNameMapper: {
    '^@queues/(.*)$': '<rootDir>/src/queues/$1',
    '^@workers/(.*)$': '<rootDir>/src/workers/$1',
    '^@processors/(.*)$': '<rootDir>/src/processors/$1',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@auth/(.*)$': '<rootDir>/src/auth/$1',
    '^@observability/(.*)$': '<rootDir>/src/observability/$1',
    '^@dashboard/(.*)$': '<rootDir>/src/dashboard/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@middleware/(.*)$': '<rootDir>/src/middleware/$1',
    '^@schemas/(.*)$': '<rootDir>/src/schemas/$1',
  },
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.test.json',
      },
    ],
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/index.ts',
    '!src/worker.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 90,
      lines: 85,
      statements: 85,
    },
  },
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  testMatch: ['<rootDir>/tests/**/*.test.ts', '<rootDir>/src/**/*.test.ts'],
  projects: [
    {
      displayName: 'unit',
      preset: 'ts-jest',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/tests/unit/**/*.test.ts'],
      moduleNameMapper: {
        '^@queues/(.*)$': '<rootDir>/src/queues/$1',
        '^@workers/(.*)$': '<rootDir>/src/workers/$1',
        '^@processors/(.*)$': '<rootDir>/src/processors/$1',
        '^@routes/(.*)$': '<rootDir>/src/routes/$1',
        '^@services/(.*)$': '<rootDir>/src/services/$1',
        '^@auth/(.*)$': '<rootDir>/src/auth/$1',
        '^@observability/(.*)$': '<rootDir>/src/observability/$1',
        '^@dashboard/(.*)$': '<rootDir>/src/dashboard/$1',
        '^@utils/(.*)$': '<rootDir>/src/utils/$1',
        '^@config/(.*)$': '<rootDir>/src/config/$1',
        '^@middleware/(.*)$': '<rootDir>/src/middleware/$1',
        '^@schemas/(.*)$': '<rootDir>/src/schemas/$1',
      },
      transform: {
        '^.+\\.tsx?$': ['ts-jest', { tsconfig: 'tsconfig.test.json' }],
      },
    },
    {
      displayName: 'integration',
      preset: 'ts-jest',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/tests/integration/**/*.test.ts'],
      testTimeout: 30000,
      moduleNameMapper: {
        '^@queues/(.*)$': '<rootDir>/src/queues/$1',
        '^@workers/(.*)$': '<rootDir>/src/workers/$1',
        '^@processors/(.*)$': '<rootDir>/src/processors/$1',
        '^@routes/(.*)$': '<rootDir>/src/routes/$1',
        '^@services/(.*)$': '<rootDir>/src/services/$1',
        '^@auth/(.*)$': '<rootDir>/src/auth/$1',
        '^@observability/(.*)$': '<rootDir>/src/observability/$1',
        '^@dashboard/(.*)$': '<rootDir>/src/dashboard/$1',
        '^@utils/(.*)$': '<rootDir>/src/utils/$1',
        '^@config/(.*)$': '<rootDir>/src/config/$1',
        '^@middleware/(.*)$': '<rootDir>/src/middleware/$1',
        '^@schemas/(.*)$': '<rootDir>/src/schemas/$1',
      },
      transform: {
        '^.+\\.tsx?$': ['ts-jest', { tsconfig: 'tsconfig.test.json' }],
      },
    },
    {
      displayName: 'smoke',
      preset: 'ts-jest',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/tests/smoke/**/*.test.ts'],
      moduleNameMapper: {
        '^@queues/(.*)$': '<rootDir>/src/queues/$1',
        '^@workers/(.*)$': '<rootDir>/src/workers/$1',
        '^@processors/(.*)$': '<rootDir>/src/processors/$1',
        '^@routes/(.*)$': '<rootDir>/src/routes/$1',
        '^@services/(.*)$': '<rootDir>/src/services/$1',
        '^@auth/(.*)$': '<rootDir>/src/auth/$1',
        '^@observability/(.*)$': '<rootDir>/src/observability/$1',
        '^@dashboard/(.*)$': '<rootDir>/src/dashboard/$1',
        '^@utils/(.*)$': '<rootDir>/src/utils/$1',
        '^@config/(.*)$': '<rootDir>/src/config/$1',
        '^@middleware/(.*)$': '<rootDir>/src/middleware/$1',
        '^@schemas/(.*)$': '<rootDir>/src/schemas/$1',
      },
      transform: {
        '^.+\\.tsx?$': ['ts-jest', { tsconfig: 'tsconfig.test.json' }],
      },
    },
  ],
};

module.exports = config;
